# Generated by Django 5.2.11 on 2026-02-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, choices=[('designer', 'Designer (UI/UX, Graphic, etc.)'), ('developer', 'Developer (Web, Mobile, Backend)'), ('writer', 'Writer (Content, Blog, Copy)'), ('marketer', 'Marketer (Digital, Social, SEO)'), ('translator', 'Translator'), ('consultant', 'Consultant & Specialist'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
